# Generated by Django 6.0.7 on 2026-08-20 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_tasks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.CharField(default=datetime.date.today, max_length=50),
        ),
    ]
