# Generated by Django 6.0.7 on 2026-09-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_tasks_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='Category',
            new_name='category',
        ),
    ]
